<?php
// $Id: panels_regions.module,v 1.3 2010/12/09 20:18:28 devkinetic Exp $

function panels_regions_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'panels_panel_context_edit_settings':

      // get regions
      $theme = variable_get('theme_default','none');
      $regions = system_region_list($theme);

      // add fieldset
      $form['conf']['disable_regions'] = array(
        '#type' => 'fieldset',
        '#title' => t('Disable Regions'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
      );

      // add in checkboxes for each region
      $conf = $form_state['handler']->conf;
      foreach ($regions as $region_id => $region_name) {
        $form['conf']['disable_regions']['disable_' . $region_id] = array(
          '#type' => 'checkbox',
          '#default_value' => $conf['disable_' . $region_id],
          '#title' => t('Disable !region_name region', array('!region_name' => $region_name)),
          '#description' => t('Check this to have the page disable the !region_name region', array(
            '!region_name' => $region_name
          )),
        );
      }

      // modify the submit handler
      $form['#submit'][] = '_panels_regions_panels_conf_submit_handler';
      break;
  }
}

// fuction for submit handler
function _panels_regions_panels_conf_submit_handler(&$form, &$form_state) {
  foreach ($form_state['values'] as $key => $value) {
    $disable = substr($key,0, 8);
    if ($disable == 'disable_') {
      $form_state['handler']->conf[$key] = $form_state['values'][$key];
    }
  }
}

// preprocess page to clear out regions
//  - the only drawback is things like body classes (eg. sidebar-left, etc) are no longer correct.
function panels_regions_preprocess_page(&$vars) {
  if ($pm_page = page_manager_get_current_page()) {
    foreach ($pm_page['handler']->conf as $key => $value) {
      $disable = substr($key,0, 8);
      if ($disable == 'disable_' && $value == 1) {
        $vars[substr($key, 8)] = '';
      }
    }
  }
}
