<?php
/**
 * @file
 * Ensure Imagecache recognises our new actions, per http://drupal.org/node/290101.
 */

function imagecache_autorotate_enable() {
  if (function_exists('imagecache_action_definitions') ) imagecache_action_definitions(TRUE);
  cache_clear_all('imagecache_actions', 'cache');
}

function imagecache_autorotate_disable() {
  if (function_exists('imagecache_action_definitions') ) imagecache_action_definitions(TRUE);
  cache_clear_all('imagecache_actions', 'cache');
}